apiVersion: v1
kind: Service
metadata:
  name: hello-svirin  # Должно совпадать с ingress
spec:
  type: NodePort
  selector:
    app: hello-svirin  # Должен совпадать с метками pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30757  # Правильно - соответствует порту контейнера
      nodePort: 30757