apiVersion: networking.k8s.io/v1                                            
kind: Ingress
metadata:
  name: hello-svirin
spec:
  rules:
  - host: hello-svirin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-svirin
            port:
              number: 80